FROM node:18-alpine

WORKDIR /app

COPY package*.json tsconfig*.json ./ 

RUN npm install --legacy-peer-deps

RUN npm install -g typescript ts-node nodemon

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]